version: "2.2"

services:
  wallet-service:
    container_name: wallet-service
    build:
      context: ./
      dockerfile: ./dockerfile.yaml
    ports:
      - '1323:1323'
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    expose:
      - 5432
    volumes: 
      - db:/var/lib/postgresql/data


volumes:
  db:
    driver: local